#!/usr/bin/env python3
"""Run a real multi-round HAD-MC PPO campaign against Qwen on one DCU.

Each PPO action launches an isolated evaluator process. The evaluator performs
activation/weight sensitivity analysis, structured pruning, sensitivity-guided
weight quantization, calibration distillation and real DCU measurements. The
controller then learns from those measured results before selecting the next
round. No synthetic candidate metrics are generated by this orchestrator.
"""

from __future__ import annotations

import argparse
import json
import math
import subprocess
import sys
import time
from pathlib import Path

import torch

from hadmc2.controllers.ppo_controller import PPOController


PRUNE_RATIOS = (0.0, 0.003, 0.007, 0.012, 0.020, 0.035)
QUANTIZATION_PROFILES = (
    {"bits": 8, "int4_layer_fraction": 0.0, "label": "INT8"},
    {"bits": 8, "int4_layer_fraction": 0.025, "label": "INT8+2.5%敏感度INT4"},
    {"bits": 8, "int4_layer_fraction": 0.05, "label": "INT8+5%敏感度INT4"},
)
STATE_DIM = 10
ACTION_DIMS = {
    "pruning": len(PRUNE_RATIOS),
    "quantization": len(QUANTIZATION_PROFILES),
    "distillation": 2,
    "fusion": 2,
    "update": 3,
}


def utc_now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    temporary.replace(path)


def progress(path: Path, phase: str, **extra: object) -> None:
    payload = {"phase": phase, "updated_at_utc": utc_now(), **extra}
    write_json(path, payload)
    print(json.dumps(payload, ensure_ascii=False), flush=True)


def sigmoid(value: float) -> float:
    return 1.0 / (1.0 + math.exp(-max(-10.0, min(10.0, value))))


def configure_conservative_prior(controller: PPOController) -> None:
    """Bias the first measured actions toward the 98% retention feasibility region."""
    with torch.no_grad():
        pruning_head = controller.policy_network.pruning_head[-1]
        pruning_head.weight.zero_()
        pruning_head.bias.copy_(torch.tensor([3.2, 2.2, 1.2, 0.2, -0.8, -1.8]))
        quantization_head = controller.policy_network.quantization_head[-1]
        quantization_head.weight.zero_()
        quantization_head.bias.copy_(torch.tensor([3.0, 0.8, -0.6]))
        controller.policy_network.distillation_mean_head[-1].weight.zero_()
        controller.policy_network.distillation_mean_head[-1].bias.zero_()


def state_tensor(
    round_index: int,
    total_rounds: int,
    previous: dict | None,
    best: dict | None,
) -> torch.Tensor:
    previous = previous or {}
    best = best or {}
    values = [
        round_index / max(total_rounds, 1),
        float(previous.get("calibration_retention_pct", 100.0)) / 100.0,
        float(previous.get("structural_compression_pct", 0.0)) / 100.0,
        float(previous.get("effective_storage_reduction_pct", 0.0)) / 100.0,
        min(float(previous.get("speedup", 1.0)), 3.0) / 3.0,
        float(previous.get("latency_reduction_pct", 0.0)) / 100.0,
        float(best.get("calibration_retention_pct", 0.0)) / 100.0,
        float(best.get("reward", 0.0)),
        1.0 if previous.get("retention_threshold_met") else 0.0,
        1.0,
    ]
    return torch.tensor(values, dtype=torch.float32).unsqueeze(0)


def decode_actions(actions: dict[str, torch.Tensor]) -> dict:
    prune_index = int(actions["pruning"].reshape(-1)[0])
    quant_index = int(actions["quantization"].reshape(-1)[0])
    distillation = actions["distillation"].reshape(-1)
    temperature = 2.0 + 4.0 * sigmoid(float(distillation[0]))
    alpha = 0.30 + 0.60 * sigmoid(float(distillation[1]))
    profile = QUANTIZATION_PROFILES[quant_index]
    return {
        "pruning_action": prune_index,
        "prune_ratio": PRUNE_RATIOS[prune_index],
        "quantization_action": quant_index,
        "quantization_label": profile["label"],
        "quant_bits": profile["bits"],
        "int4_layer_fraction": profile["int4_layer_fraction"],
        "distillation_temperature": round(temperature, 5),
        "distillation_alpha": round(alpha, 5),
        "fusion_action": int(actions["fusion"].reshape(-1)[0]),
        "update_action": int(actions["update"].reshape(-1)[0]),
    }


def evaluator_command(args: argparse.Namespace, round_dir: Path, candidate_id: str, action: dict) -> list[str]:
    return [
        sys.executable,
        "-u",
        str(Path(__file__).with_name("qwen_real_compression.py")),
        "--output-dir",
        str(round_dir),
        "--model-cache",
        args.model_cache,
        "--model-id",
        args.model_id,
        "--candidate-id",
        candidate_id,
        "--prune-ratio",
        str(action["prune_ratio"]),
        "--quality-weight",
        "0.88",
        "--storage-weight",
        "0.07",
        "--latency-weight",
        "0.05",
        "--quant-bits",
        str(action["quant_bits"]),
        "--int4-layer-fraction",
        str(action["int4_layer_fraction"]),
        "--distillation-temperature",
        str(action["distillation_temperature"]),
        "--distillation-alpha",
        str(action["distillation_alpha"]),
    ]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--node", required=True)
    parser.add_argument("--rounds", type=int, default=4)
    parser.add_argument("--seed", type=int, default=20260724)
    parser.add_argument("--model-cache", default="/models/qwen2.5-7b-instruct")
    parser.add_argument("--model-id", default="Qwen/Qwen2.5-7B-Instruct")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    progress_path = output_dir / "QLIGHT_PPO_PROGRESS.json"
    result_path = output_dir / "QLIGHT_PPO_CAMPAIGN.json"
    controller_path = output_dir / "QLIGHT_PPO_CONTROLLER.pt"
    torch.manual_seed(args.seed)
    controller = PPOController(
        state_dim=STATE_DIM,
        action_dims=ACTION_DIMS,
        device="cpu",
        lr=8e-4,
        entropy_coef=0.02,
    )
    configure_conservative_prior(controller)
    trajectory: list[dict] = []
    previous: dict | None = None
    best: dict | None = None

    progress(
        progress_path,
        "ppo_initializing",
        node=args.node,
        total_rounds=args.rounds,
        retention_threshold_pct=98.0,
    )
    for round_index in range(1, args.rounds + 1):
        state = state_tensor(round_index - 1, args.rounds, previous, best)
        actions, log_prob, value = controller.select_actions(state)
        decoded = decode_actions(actions)
        candidate_id = (
            f"ppo-r{round_index:02d}-p{decoded['prune_ratio']:.3f}-"
            f"q{decoded['quant_bits']}-m{decoded['int4_layer_fraction']:.3f}"
        ).replace(".", "d")
        round_dir = output_dir / f"round-{round_index:02d}-{candidate_id}"
        round_dir.mkdir(parents=True, exist_ok=True)
        progress(
            progress_path,
            "ppo_evaluating",
            node=args.node,
            round=round_index,
            total_rounds=args.rounds,
            action=decoded,
            candidate_id=candidate_id,
            trajectory=trajectory,
        )
        log_path = round_dir / "evaluator.log"
        command = evaluator_command(args, round_dir, candidate_id, decoded)
        with log_path.open("w", encoding="utf-8") as log_file:
            completed = subprocess.run(command, stdout=log_file, stderr=subprocess.STDOUT, check=False)
        candidate_path = round_dir / "QLIGHT_REAL_QWEN_CANDIDATE.json"
        failure = None
        candidate: dict = {}
        if completed.returncode == 0 and candidate_path.exists():
            payload = json.loads(candidate_path.read_text(encoding="utf-8"))
            candidate = payload["candidate"]
            reward = float(candidate["reward"])
        else:
            failure = f"evaluator exited with code {completed.returncode}"
            reward = -3.0

        transition = {
            "round": round_index,
            "node": args.node,
            "candidate_id": candidate_id,
            "action": decoded,
            "reward": reward,
            "candidate": candidate,
            "failure": failure,
            "artifact": str(round_dir.relative_to(output_dir)),
        }
        trajectory.append(transition)
        if candidate and (
            best is None
            or (
                bool(candidate.get("retention_threshold_met")),
                float(candidate.get("reward", -999.0)),
            )
            > (
                bool(best.get("retention_threshold_met")),
                float(best.get("reward", -999.0)),
            )
        ):
            best = candidate
        previous = candidate or previous

        stored_actions = {key: tensor.squeeze(0).detach() for key, tensor in actions.items()}
        controller.buffer.add(
            state.squeeze(0).detach(),
            stored_actions,
            log_prob.squeeze(0).detach(),
            reward,
            round_index == args.rounds,
            value.squeeze().detach(),
        )
        update_info = None
        if controller.buffer.size >= 2 or round_index == args.rounds:
            update_info = controller.update(
                batch_size=min(2, controller.buffer.size),
                num_epochs=3,
            )
            transition["ppo_update"] = update_info
            controller.save(str(controller_path))
        progress(
            progress_path,
            "ppo_feedback",
            node=args.node,
            round=round_index,
            total_rounds=args.rounds,
            reward=reward,
            ppo_update=update_info,
            best_candidate=best,
            trajectory=trajectory,
        )

    qualified = [
        item for item in trajectory
        if item["candidate"] and item["candidate"].get("retention_threshold_met")
    ]
    result = {
        "product": "QLight",
        "experiment": "real_qwen_hadmc_ppo_campaign",
        "node": args.node,
        "model_id": args.model_id,
        "rounds": args.rounds,
        "retention_threshold_pct": 98.0,
        "threshold_met": bool(qualified),
        "best_candidate": best,
        "trajectory": trajectory,
        "evidence_scope": {
            "sensitivity": "calibration activation and model weight sensitivity",
            "pruning": "real structured Qwen SwiGLU channel pruning",
            "quantization": "real sensitivity-guided weight quantization/dequantization; logical storage is measured without claiming an INT DCU kernel",
            "distillation": "real per-token soft-logit calibration distillation; not full fine tuning",
            "ppo": "HAD-MC PPO policy is updated from each real candidate reward and measurement",
            "quality": "98% is a calibration-logit retention gate, not a benchmark accuracy claim",
        },
        "completed_at_utc": utc_now(),
    }
    write_json(result_path, result)
    progress(
        progress_path,
        "completed",
        node=args.node,
        result_file=result_path.name,
        threshold_met=result["threshold_met"],
        best_candidate=best,
        trajectory=trajectory,
    )


if __name__ == "__main__":
    main()
